export const colleges = [
  "College 1",
  "College 2",
  "College 3",
  "College of Engineering",
  "National Institute of Technology",
  "Indian Institute of Technology",
];

export const university = [
  "University 1",
  "UEM",
  "MAKAUT",
  "University 4",
  "University 5",
  "University 6",
];

export const courses = [
  "Course 1",
  "Course 2",
  "Course 3",
  "BTech",
  "MTech",
  "MBA",
  "BBA",
  "BCA",
  "MCA",
  "BSc",
  "MSc",
  "BCom",
  "MCom",
];
/* specializations */
export const specializations = [
  "Computer Science",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "English",
  "Commerce",
  "Arts",
  "Social Studies",
  "History",
  "Geography",
  "Economics",
  "Law",
  "Philosophy",
  "Sociology",
  "Psychology",
  "Anthropology",
  "Linguistics",
  "Literature",
  "Art",
  "Design",
  "Architecture",
  "Music",
  "Theater",
  "Dance",
  "Cooking",
  "Photography",
  "Journalism",
  "Business Administration",
  "Marketing",
  "Finance",
  "Accountancy",
  "Tourism",
  "Hospitality",
  "Restaurant Management",
  "Retail Management",
  "Supply Chain Management",
];
/* grading_systems */
export const grading_systems = [
  "Scale 10 Grading System",
  "Scale 4 Grading System",
  "% Marks of 100 Maximum",
  "Course Requires a Pass",
];

export const diploma_st_uni = [
  "State Board 1",
  "State Board 2",
  "university 1",
  "university 2",
  "university 3",
  "university 4",
  "university 5",
  "university 6",
];

export const savedAcademicData = [
  {
    id: 1,
    level: "tenth",
    data: {
      state: "West Bengal",
      board: "CBSE",
      schoolName: "St. Xavier's High School",
      year: "2015",
      totalMarks: "500",
      marksObtain: "450",
      percentage: "90",
      transcriptFile: "tenth_transcript.pdf",
      certificateFile: "tenth_certificate.pdf",
    },
  },
  {
    id: 2,
    level: "twelfth",
    data: {
      state: "West Bengal",
      board: "CBSE",
      schoolName: "St. Xavier's High School",
      year: "2017",
      totalMarks: "500",
      marksObtain: "435",
      percentage: "87",
      transcriptFile: "twelfth_transcript.pdf",
      certificateFile: "twelfth_certificate.pdf",
    },
  },
  {
    id: 3,
    level: "undergraduate",
    data: {
      state: "West Bengal",
      university: "Demo University",
      college: "Demo College",
      course: "BTech",
      year: "2025",
      cgpa: "8.5",
      percentage: "85",
      transcriptFile: "btech_transcript.pdf",
      certificateFile: "btech_certificate.pdf",
    },
  },
];
