const Candidatelist = [
  {
    id: 1,
    name: "Abhishek Dey",
    address: "Newtown",
    pan_verified: true,
    aadhar_verified: true,
    voter_verified: true,
    license_verified: false,
    passport_verified: false,
    dob: "13-10-2000",
    phone: "9876543210",
    email: "ab.dey2000@gmail.com",
    gender: "male",
  },
  {
    id: 2,
    name: "Rohit Sharma",
    address: "Salt Lake",
    pan_verified: true,
    aadhar_verified: false,
    voter_verified: true,
    license_verified: true,
    passport_verified: false,
    dob: "21-05-1998",
    phone: "9876543211",
    email: "rohit.sharma@gmail.com",
    gender: "male",
  },
  {
    id: 3,
    name: "Sohini Das",
    address: "Park Street",
    pan_verified: false,
    aadhar_verified: true,
    voter_verified: false,
    license_verified: true,
    passport_verified: true,
    dob: "10-12-1995",
    phone: "9876543212",
    email: "sohini.das@gmail.com",
    gender: "female",
  },
  {
    id: 4,
    name: "Amit Roy",
    address: "Howrah",
    pan_verified: true,
    aadhar_verified: true,
    voter_verified: true,
    license_verified: false,
    passport_verified: true,
    dob: "05-07-1999",
    phone: "9876543213",
    email: "amit.roy@gmail.com",
    gender: "male",
  },
  {
    id: 5,
    name: "Priya Saha",
    address: "Ballygunge",
    pan_verified: false,
    aadhar_verified: false,
    voter_verified: true,
    license_verified: true,
    passport_verified: false,
    dob: "17-09-1997",
    phone: "9876543214",
    email: "priya.saha@gmail.com",
    gender: "female",
  },
  {
    id: 6,
    name: "Rajesh Gupta",
    address: "Dum Dum",
    pan_verified: true,
    aadhar_verified: false,
    voter_verified: false,
    license_verified: true,
    passport_verified: true,
    dob: "22-03-1994",
    phone: "9876543215",
    email: "rajesh.gupta@gmail.com",
    gender: "male",
  },
  {
    id: 7,
    name: "Ankita Ghosh",
    address: "Gariahat",
    pan_verified: true,
    aadhar_verified: true,
    voter_verified: true,
    license_verified: false,
    passport_verified: false,
    dob: "30-08-1996",
    phone: "9876543216",
    email: "ankita.ghosh@gmail.com",
    gender: "female",
  },
  {
    id: 8,
    name: "Vikram Sen",
    address: "Rajarhat",
    pan_verified: false,
    aadhar_verified: true,
    voter_verified: false,
    license_verified: true,
    passport_verified: true,
    dob: "19-11-1992",
    phone: "9876543217",
    email: "vikram.sen@gmail.com",
    gender: "male",
  },
  {
    id: 9,
    name: "Meera Chakraborty",
    address: "Behala",
    pan_verified: true,
    aadhar_verified: false,
    voter_verified: true,
    license_verified: false,
    passport_verified: true,
    dob: "08-04-1993",
    phone: "9876543218",
    email: "meera.chakraborty@gmail.com",
    gender: "female",
  },
  {
    id: 10,
    name: "Sourav Banerjee",
    address: "Shyambazar",
    pan_verified: true,
    aadhar_verified: true,
    voter_verified: true,
    license_verified: true,
    passport_verified: false,
    dob: "26-06-1995",
    phone: "9876543219",
    email: "sourav.banerjee@gmail.com",
    gender: "male",
  },
];

export default Candidatelist;
